FROM alpine:3.16 as builder
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update && apk add tzdata python3  \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /usr
COPY fxckToday fxckToday
